import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/shanba">
          <a>login</a>
        </Link>
        <Link href="/juma">
          <a>Visit /team (redirects to /about)</a>
        </Link>
        <Link href={{
          pathname: 'juma'
        }
        }>
          <a>profile</a>
        </Link>
      </main>


    </div >
  )
}
